### ISSUE TITLE
Don't delete suggestions from review channel

### ISSUE THREAD

**Issue by Ibotmealot** [OtterDevelopment/Astro#10]
**Is your feature request related to a problem? Please describe.**
Maybe this is just something I have a use case for, so maybe a config option would be best, but if a suggestion is approved or denied currently it's deleted. 

**Describe the solution you'd like**
A footer should be added to the embed saying something like "Approved by x" or "Denied by x" with the reviewers avatar as the footer icon. Also maybe make the timestamp of the footer when it was reviewed? Finally, disable the approve and deny buttons that way they can't be pushed. 

**Describe alternatives you've considered**
None

**Additional context**
This is just me going on at this point, hope it makes sense.

**Comment by xPolar** [comment]
This was implemented in [`9393cb4`](https://github.com/OtterDevelopment/Astro/commit/9393cb417557b6d7178ff4c4eb03c883b5cb409f).
