### ISSUE TITLE
Suggestion: Archive deleted suggestions & implemented ones

### ISSUE THREAD

**Issue by Ibotmealot** [OtterDevelopment/Astro#2]
The ability to set a channel where deleted and suggestions marked as implemented will be sent to, this way the suggestions channel isn't doesn't get cluttered.

**Comment by xPolar** [comment]
Currently you can set individual channels for decisions to go into, for example denied suggestions go into one channel, implemented suggestions go into another. You could just delete the message for the suggestion, thus it goes into the other suggestion channels to be archived. However, this would mean you can't make a decision on the suggestion anymore as Astro depends on the suggestion message to exist to modify the outcome.
