### ISSUE TITLE
Suggestion: Suggestion Role Pings

### ISSUE THREAD

**Issue by Ibotmealot** [OtterDevelopment/Astro#3]
Set a role to be pinged when a suggestion is approved and sent to the suggestions channel.

**Comment by xPolar** [comment]
I'll add this feature along with Trello sometime this weekend.

**Comment by xPolar** [comment]
This has been implemented in [`ae24c00`](https://github.com/OtterDevelopment/Astro/commit/ae24c00cae7486cff88f3178cc59ea7dc9c0b6a9).
