### ISSUE TITLE
Suggestion: Have the ability to mark suggestions for review

### ISSUE THREAD

**Issue by Ibotmealot** [OtterDevelopment/Astro#4]
A mode where suggestions must be approved by server staff / admins (a role that you can also set with a command), and then you must also set a channel where these suggestions go first. Server staff can then either approve or deny the suggestion, if it's approved it goes to the suggestion channel. Hope that makes sense, once again this is something Suggestor offers [here](https://suggester.js.org/#/config/mode).

**Comment by xPolar** [comment]
I've already recieved this suggestion in our [Support Server](https://inv.wtf/astro), and do intend to implement it when I get the time.

**Comment by xPolar** [comment]
This has been implemented in [`3525e6`](https://github.com/OtterDevelopment/Astro/commit/3525e60a690a4336d9a8a2ca6c6c6a6ea6fc0987).
