### ISSUE TITLE
Suggestion: Improve help command

### ISSUE THREAD

**Issue by Ibotmealot** [OtterDevelopment/Astro#6]
Maybe add some dropdowns to the **/help** command which explain the usage of some things? It seems pretty bare bones right now.

**Comment by xPolar** [comment]
I will do that, when I implemented the help command I didn't really know what to put as all the information for all of the commands is located within the slash commands. I'll look into implementing it during the weekend.

**Comment by xPolar** [comment]
@Ibotmealot I wasn't really able to think of any information to put into the slash command, for me to properly make it show all of the slash commands and their sub commands I would have to rework the entire slash command structure, which is just something I do not intend to do at the time.
