### ISSUE TITLE
Suggestion: Delete command

### ISSUE THREAD

**Issue by Ibotmealot** [OtterDevelopment/Astro#7]
Ability to delete an already approved suggestion, and send it to the denied channel if one is set. [link](https://suggester.js.org/#/staff/delete)

**Comment by xPolar** [comment]
Will do during the weekend.

**Comment by xPolar** [comment]
@Ibotmealot I'm having a hard time understanding what you actually want in this feature, could you elaborate?

**Comment by xPolar** [comment]
This has been implemented in [`591fac6`](https://github.com/OtterDevelopment/Astro/commit/591fac60135bd70322d68f2a0ff228c3e2cacb0b).

**Comment by xPolar** [comment]
Please note that you do require a public-facing log channel for this to actually function, I tried to fit that into the slash command description, however, it wouldn't fit into the one hundred character limit.
