### ISSUE TITLE
Modal Popup

### ISSUE THREAD

**Issue by Ibotmealot** [OtterDevelopment/Astro#9]
**Is your feature request related to a problem? Please describe.**
I think users should be informed on why their suggestions are denied

**Describe the solution you'd like**
An optional modal should pop up if you click the deny button and it should ask why you're denying the suggestion. The reason will then be sent to user who submitted it. 

**Describe alternatives you've considered**
DMing the user yourself, idk lmao? 

**Additional context**
N/A

**Comment by xPolar** [comment]
This has been implemented in [`ff5cf37`](https://github.com/OtterDevelopment/Astro/commit/ff5cf37dcd9939a81152eed6021eba55d243b4b9).
